# Generated by Django 5.2.15 on 2026-06-09 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIProviderSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        default="OpenAI", max_length=80, verbose_name="Provider"
                    ),
                ),
                (
                    "model",
                    models.CharField(blank=True, max_length=120, verbose_name="Model"),
                ),
                ("base_url", models.URLField(blank=True, verbose_name="Base URL")),
                (
                    "api_key",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="API Key"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ImportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("imported_rows", models.PositiveIntegerField(default=0)),
                ("error_rows", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OptionGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ReferenceSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="來源名稱")),
                ("url", models.URLField(blank=True, verbose_name="來源網址")),
                ("citation_note", models.TextField(blank=True, verbose_name="引用資訊")),
                (
                    "accessed_on",
                    models.DateField(blank=True, null=True, verbose_name="存取日期"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OptionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("color", models.CharField(blank=True, max_length=20)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="questions.optiongroup",
                    ),
                ),
            ],
            options={
                "ordering": ["group__name", "sort_order", "name"],
                "unique_together": {("group", "name")},
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_domain",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="原AI領域範疇"
                    ),
                ),
                ("stem", models.TextField(blank=True, verbose_name="題幹")),
                ("choice_a", models.TextField(blank=True, verbose_name="選項 A")),
                ("choice_b", models.TextField(blank=True, verbose_name="選項 B")),
                ("choice_c", models.TextField(blank=True, verbose_name="選項 C")),
                ("choice_d", models.TextField(blank=True, verbose_name="選項 D")),
                (
                    "answer",
                    models.CharField(
                        blank=True,
                        choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                        max_length=1,
                        verbose_name="答案",
                    ),
                ),
                ("revised_stem", models.TextField(blank=True, verbose_name="新題幹")),
                (
                    "revised_choice_a",
                    models.TextField(blank=True, verbose_name="新選項 A"),
                ),
                (
                    "revised_choice_b",
                    models.TextField(blank=True, verbose_name="新選項 B"),
                ),
                (
                    "revised_choice_c",
                    models.TextField(blank=True, verbose_name="新選項 C"),
                ),
                (
                    "revised_choice_d",
                    models.TextField(blank=True, verbose_name="新選項 D"),
                ),
                (
                    "revised_answer",
                    models.CharField(
                        blank=True,
                        choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                        max_length=1,
                        verbose_name="新答案",
                    ),
                ),
                (
                    "revised_explanation",
                    models.TextField(blank=True, verbose_name="新解析"),
                ),
                (
                    "difficulty",
                    models.CharField(blank=True, max_length=80, verbose_name="難易度"),
                ),
                (
                    "main_dimension",
                    models.CharField(blank=True, max_length=160, verbose_name="主層面"),
                ),
                (
                    "sub_dimension",
                    models.CharField(blank=True, max_length=160, verbose_name="次層面"),
                ),
                (
                    "certification_note",
                    models.TextField(blank=True, verbose_name="認證內容說明"),
                ),
                (
                    "classification_basis",
                    models.TextField(blank=True, verbose_name="分類依據"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status_option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="status_questions",
                        to="questions.optionitem",
                        verbose_name="狀態",
                    ),
                ),
                (
                    "type_option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="type_questions",
                        to="questions.optionitem",
                        verbose_name="類型",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ReferenceFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="檔案名稱")),
                (
                    "file",
                    models.FileField(upload_to="references/", verbose_name="參考檔案"),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="questions.referencesource",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
