# Generated by Django 5.2.15 on 2026-06-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="original_domain",
            field=models.CharField(
                blank=True,
                choices=[("資料隱私、資料安全與合規", "資料隱私、資料安全與合規"), ("資料偏見與公平性", "資料偏見與公平性")],
                max_length=200,
                verbose_name="原AIE領域範疇",
            ),
        ),
    ]
