# Generated by Django 5.2.15 on 2026-06-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0002_alter_question_original_domain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="difficulty",
            field=models.CharField(
                blank=True,
                choices=[("基礎", "基礎"), ("進階", "進階")],
                max_length=80,
                verbose_name="難易度",
            ),
        ),
    ]
