# Generated by Django 5.2.15 on 2026-06-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0003_alter_question_difficulty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="revised_explanation",
            field=models.TextField(blank=True, verbose_name="解析"),
        ),
    ]
