# Generated by Django 5.2.15 on 2026-06-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0004_alter_question_revised_explanation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="main_dimension",
            field=models.CharField(
                blank=True, default="AI政策法制", max_length=160, verbose_name="主層面"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="sub_dimension",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AI法規與資安風險管理", "AI法規與資安風險管理"),
                    ("AI應用下的倫理準則與智慧財產權實務", "AI應用下的倫理準則與智慧財產權實務"),
                ],
                max_length=160,
                verbose_name="次層面",
            ),
        ),
    ]
