# Generated by Django 5.2.15 on 2026-06-09 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0005_alter_question_main_dimension_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aiprovidersetting",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="aiprovidersetting",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="啟用"),
        ),
        migrations.AddField(
            model_name="aiprovidersetting",
            name="name",
            field=models.CharField(
                default="Default", max_length=120, unique=True, verbose_name="名稱"
            ),
        ),
        migrations.AlterField(
            model_name="aiprovidersetting",
            name="model",
            field=models.CharField(blank=True, max_length=120, verbose_name="預設 Model"),
        ),
        migrations.CreateModel(
            name="AIModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_id", models.CharField(max_length=200, verbose_name="Model ID")),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=200, verbose_name="顯示名稱"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="啟用")),
                ("loaded_at", models.DateTimeField(auto_now=True)),
                (
                    "api_setting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="models",
                        to="questions.aiprovidersetting",
                    ),
                ),
            ],
            options={
                "ordering": ["api_setting__name", "model_id"],
                "unique_together": {("api_setting", "model_id")},
            },
        ),
    ]
