# Generated by Django 5.2.15 on 2026-06-09 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0006_alter_aiprovidersetting_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DatabaseBackup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.CharField(max_length=200, verbose_name="備份原因")),
                ("file_path", models.CharField(max_length=500, verbose_name="備份檔案")),
                (
                    "created_by",
                    models.CharField(blank=True, max_length=150, verbose_name="建立者"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="question",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="完成時間"),
        ),
        migrations.AddField(
            model_name="question",
            name="is_completed",
            field=models.BooleanField(default=False, verbose_name="已完成鎖定"),
        ),
        migrations.CreateModel(
            name="AIDatabaseOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt", models.TextField(verbose_name="提示詞")),
                ("response", models.TextField(blank=True, verbose_name="AI 回覆")),
                ("summary", models.TextField(blank=True, verbose_name="執行摘要")),
                (
                    "created_by",
                    models.CharField(blank=True, max_length=150, verbose_name="執行者"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "backup",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="questions.databasebackup",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
