# Generated by Django 5.2.15 on 2026-06-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0007_databasebackup_question_completed_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemWritingReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "main_dimension",
                    models.CharField(
                        default="AI政策法制", max_length=160, verbose_name="主層面"
                    ),
                ),
                ("sub_dimension", models.CharField(max_length=160, verbose_name="次層面")),
                ("title", models.CharField(max_length=200, verbose_name="標題")),
                ("content", models.TextField(verbose_name="命題參考內容")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="排序"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="啟用")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["main_dimension", "sub_dimension", "sort_order", "id"],
                "unique_together": {("main_dimension", "sub_dimension", "title")},
            },
        ),
    ]
